name: Build

on:
  workflow_dispatch:
    inputs:
      name:
        default: VideoLab Virtual Camera
      count:
        default: '2'

env:
  SOLUTION_FILE_PATH: ./softcam.sln

jobs:

  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    outputs:
      count: ${{ steps.count.outputs.count }}
    steps:
    - id: count
      run: |
        count=$(seq 1 "${{ github.event.inputs.count }}" | jq -cs '.')
        echo "count=$count" >> "$GITHUB_OUTPUT"

  build:
    name: Build ${{ matrix.name }} ${{ matrix.count }}
    runs-on: windows-latest
    needs: matrix
    strategy:
      matrix:
        name: 
          - ${{ github.event.inputs.name }}
        count: ${{ fromJSON(needs.matrix.outputs.count) }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v5

    - name: Replace Strings
      uses: richardrigutins/replace-in-files@v2
      with:
        files: src/softcam/softcam.cpp
        search-text: DirectShow Softcam
        replacement-text: ${{matrix.name }} ${{ matrix.count }}
        encoding: utf8

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore Packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Libraries
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Rename Files
      shell: cmd
      run: move x64\Release\softcam.dll vcam${{ matrix.count }}.dll

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          vcam${{ matrix.count }}.dll
        name: '1.0.0'
        tag_name: '1.0.0'
        token: ${{ secrets.GH_PAT }}